server:
  port: 2023
spring:
  # DataSource Config
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gallywix?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-flex:
  global-config:
    logic-delete-column: del_flag
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
application:
  security:
    jwt:
      secret-key: U2FsdGVkX18epMj+KK0TtMyZJzvr45zahWHKpl4+kSg=
      expiration: 3600000 # a day
      refresh-token:
        expiration: 604800000 # 7 days